name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python_ci:
    name: Python CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd lib/time-parser-py
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install maturin pytest

      - name: Build and develop with maturin
        run: |
          cd lib/time-parser-py
          source .venv/bin/activate
          maturin develop

      - name: Run tests
        run: |
          cd lib/time-parser-py
          source .venv/bin/activate
          pytest
